name: "Commit Message Lint"

on:
  push:
    branches:
      - "**" # all branches
  pull_request:
    branches:
      - "**" # all PR targets

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install Commitlint
        run: npm install -g @commitlint/{cli,config-conventional}

      - name: Lint commits
        run: npx commitlint --config commitlint.config.js --from=origin/main --to=HEAD
